spring:
  config:
    import: optional:file:.env[.properties]
  h2:
    console:
      enabled: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      # Disable SQL initialization
      mode: never

# LocationIQ API configuration using environment variables
locationiq:
  api:
    key: ${LOCATIONIQ_API_KEY:your-default-api-key-here}
    base-url: ${LOCATIONIQ_API_BASE_URL:https://locationiq.com/v1}
