spring:
  h2:
    console:
      enabled: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  sql:
    init:
      # Disable SQL initialization
      mode: never
  config:
    active: 
    import: optional:file:.env.properties

# LocationIQ API configuration using environment variables
locationiq:
  api:
    key: ${LOCATIONIQ_API_KEY:your-default-api-key-here}
    base-url: ${LOCATIONIQ_API_BASE_URL:https://locationiq.com/v1}
