spring:
  profiles: prod
  h2:
    console:
      enabled: true
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  sql:
    init:
      # Disable SQL initialization
      mode: never
  config:
    active: 
      on-profile: prod
    import: optional:file:.env.properties
